name: API CI

on:
  push:
    branches: [ main ]
    paths:
    - 'api/**'

  pull_request:
    branches: [ main ]
    paths:
    - 'api/**'

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      working-directory: api

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: yarn install --frozen-lockfile
    - name: Build
      run: yarn build --if-present
    - name: Test
      run: yarn test
